[serveur]
myserver ansible_host=YOUR.SERVER.IP ansible_user=root ansible_port=22

users:
  - username: michael
    password: "$6$DFE7A3...HASH..."
    fullname: "Michael B."
    phone: "+237698782086"
    shell: "/bin/bash"
    email: "michaelbenfiang@gmail.com"

  - username: jean
    password: "$6$A9FGD1...HASH..."
    fullname: "Jean M."
    phone: "+237690888752"
    shell: "/bin/zsh"
    email: "effamebengajean1@gmail.com"

---

- hosts: serveur
  become: yes

  vars_files:
    - users.yml

  tasks:

    - name: Créer les utilisateurs
      user:
        name: "{{ item.username }}"
        comment: "{{ item.fullname }}, {{ item.phone }}"
        shell: "{{ item.shell }}"
        password: "{{ item.password }}"
        groups: sudo
        state: present
      loop: "{{ users }}"

    - name: Forcer le changement de mot de passe
      command: chage -d 0 {{ item.username }}
      loop: "{{ users }}"

    - name: Définir quota disque
      command: setquota -u {{ item.username }} 15728640 15728640 0 0 /
      loop: "{{ users }}"

    - name: Limiter la mémoire par systemd
      copy:
        dest: "/etc/systemd/system/user-{{ item.username }}.slice"
        content: |
          [Service]
          MemoryMax=20%
      loop: "{{ users }}"

    - name: Recharger systemd
      systemd:
        daemon_reload: yes

    - name: Envoyer un mail aux utilisateurs
      mail:
        to: "{{ item.email }}"
        subject: "Informations de connexion"
        body: |
          Bonjour {{ item.fullname }},

          Votre compte a été créé sur le serveur.
          Adresse IP : {{ ansible_host }}
          Port SSH : 2222
          Nom d’utilisateur : {{ item.username }}

          Veuillez changer votre mot de passe dès la première connexion.

          Cordialement,
          Administrateur Système
      loop: "{{ users }}"
